name: K6 Performance Test

on:
  push:
    branches: [ main ] 
  pull_request:
    branches: [ main ] 

jobs:
  performance-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      
      - name: Run k6 test
        uses: grafana/k6-action@v0.3.1
        with:
          path: Tests/k6_poc_test.js
