name: K6 Performance Test

on:
  push:
    branches: [ main ] 
  pull_request:
    branches: [ main ] 

jobs:
  performance-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run k6 test
        id: k6
        uses: grafana/k6-action@v0.2.0
        with:
          script: Tests/k6_poc_test.js
